Repository SWM-METEOR/finote-backend, pull requests merged in 2023-08, with the labels that each got.

#42 CD 환경 구축
  .DS_Store
  .github/workflows/build-deploy.yml
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: 👀 review needed, 💻 chore

#45 [FIN-138] refactor: DTO 함수 인사 전달 시 변수명 변경, Domain 로직 수정
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/request/GoogleAccessTokenRequest.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleLoginResponse.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleOauthUserInfoResponse.java
  src/main/java/kr/co/finote/backend/src/HealthCheckController.java
  src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/AiSearchResponse.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/PostArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/AiSearchService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/utils/ChatGptResponseResolver.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/SessionService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 👀 review needed, 👀 refactor

#47 Update HealthCheck Controller
  src/main/java/kr/co/finote/backend/src/HealthCheckController.java
Labels: 🐞 bug

#48 [FIN-125] 세션 값 관련 로직 수정
  src/main/java/kr/co/finote/backend/global/advice/GlobalRestControllerAdvice.java
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/global/interceptor/SessionInterceptor.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 👀 review needed, 👀 refactor

#49 [FIN-157] feat: swagger https 설정
  src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java
Labels: 🐞 bug, 👀 review needed

#50 [FIN-157] feat: swagger https 설정
  src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java
Labels: 🐞 bug, 👀 review needed

#52 [FIN-161] feat: 유저 로그인 상태 확인 API
  scripts/deploy.sh
  src/main/java/kr/co/finote/backend/BackendApplication.java
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/src/HealthCheckController.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/service/SessionService.java
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#53 [FIN-162] feat: 배포 쉘 스크립트 수정
  scripts/deploy.sh
Labels: 🐞 bug, 👀 review needed

#54 [FIN-162] feat: 배포 쉘 스크립트 수정
  scripts/deploy.sh
Labels: 🐞 bug, 👀 review needed

#55 [FIN-162] feat: 배포 쉘 스크립트 수정
  src/main/java/kr/co/finote/backend/src/HealthCheckController.java
Labels: 🐞 bug, 👀 review needed

#56 [FIN-163] feat: 백엔드 구글 테스트용 API 구현
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/GoogleLoginCodeResponse.java
Labels: 💪🏻 feature, 👀 review needed

#57 [FIN-167] feat: 서버 에러 로그 slack 연동
  .gitignore
  build.gradle
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/HealthCheckController.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/resources/application.yml
  src/main/resources/logback-slack.xml
Labels: 💪🏻 feature, 👀 review needed

#58 [FIN-171] feat: 엘라스틱 서치 Spring Boot 연동
  build.gradle
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchConfig.java
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#60 Revert "[FIN-171] feat: 엘라스틱 서치 Spring Boot 연동"
  build.gradle
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchConfig.java
  src/main/resources/application.yml
Labels: 🐞 bug

#61 [FIN-176] 로그아웃 API 구현
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
  src/main/java/kr/co/finote/backend/global/jwt/JwtToken.java
  src/main/java/kr/co/finote/backend/src/user/api/JwtApi.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
Labels: 💪🏻 feature, 👀 review needed

#62 [FIN-176] 로그아웃 API 구현
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
Labels: 🐞 bug, 👀 review needed

#64 [FIN-171] feat: 엘라스틱 서치 Spring Boot 연동
  build.gradle
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchConfig.java
Labels: 💪🏻 feature, 👀 review needed

#65 [FIN-195] feat: 스웨거 JWT 토큰 설정
  src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java
Labels: 💪🏻 feature, 👀 review needed

#66 [FIN-198] feat:리프레시 토큰 관련 Exception 통합
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
Labels: 💪🏻 feature

#67 fix: 아티클 저장 시 로그인 유저 정보 연결
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 🐞 bug

#68 [FIN-173] 내 블로그 글 리스트 조회 API
  src/main/java/kr/co/finote/backend/global/annotation/Login.java
  src/main/java/kr/co/finote/backend/global/argumentresolver/LoginUserArgumentResolver.java
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/ArticlePreviewRequest.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/UserArticlesResponse.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#73 [FIN-223] 메인 페이지 글 모아보기 API
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
  src/main/java/kr/co/finote/backend/global/utils/StringUtils.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticlePreviewResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/ElasticService.java
  src/main/java/kr/co/finote/backend/src/common/api/TrendArticleApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#74 [FIN-228] 팔로우/언팔로우 API 구현
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/common/api/CommonApi.java
  src/main/java/kr/co/finote/backend/src/common/api/TrendArticleApi.java
  src/main/java/kr/co/finote/backend/src/common/domain/FollowInfo.java
  src/main/java/kr/co/finote/backend/src/common/dto/FollowResultResponse.java
  src/main/java/kr/co/finote/backend/src/common/repository/FollowInfoRepository.java
  src/main/java/kr/co/finote/backend/src/common/service/FollowService.java
Labels: 💪🏻 feature, 👀 review needed

#76 Elasticsearch Document String -> Date 변환 로직 수정
  src/main/java/kr/co/finote/backend/src/article/service/ElasticService.java
Labels: 🐞 bug, 👀 review needed

#77 [FIN-226] 팔로잉/팔로워 목록 API
  src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/common/api/CommonApi.java
  src/main/java/kr/co/finote/backend/src/common/dto/response/FollowResultResponse.java
  src/main/java/kr/co/finote/backend/src/common/dto/response/FollowUserListResponse.java
  src/main/java/kr/co/finote/backend/src/common/dto/response/FollowUserResponse.java
  src/main/java/kr/co/finote/backend/src/common/repository/FollowInfoRepository.java
  src/main/java/kr/co/finote/backend/src/common/service/FollowService.java
  src/main/java/kr/co/finote/backend/src/user/api/JwtApi.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
Labels: 💪🏻 feature, 👀 review needed

#78 fix: 팔로잉 목록 조회 로직 수정
  src/main/java/kr/co/finote/backend/src/common/service/FollowService.java
Labels: 🐞 bug, 👀 review needed

#79 [FIN-233] feat: 빈 문자열 null 대신 "" 반환
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/domain/Keyword.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/DragArticleRequest.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
Labels: 💪🏻 feature, 👀 review needed

#81 [FIN-254] feat: 글 작성 API 응답 형식 수정
  src/main/java/kr/co/finote/backend/src/article/dto/response/PostArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature, 👀 review needed

#82 [FIN-264] Redis 환경 구축
  build.gradle
  src/main/java/kr/co/finote/backend/BackendApplication.java
  src/main/java/kr/co/finote/backend/global/config/RedisCacheConfig.java
  src/main/java/kr/co/finote/backend/global/config/RedisConfig.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/domain/ArticleLike.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/LikeResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleLikeRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/common/service/FollowService.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#83 블로그 글 수정 및 삭제 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchConfig.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature, 👀 review needed

#86 elasticserach 데이터 받아오는 중 thumbnail null로 내려오는 에러 해결
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/ArticleKeyword.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticlePreviewResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleLikeRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleKeywordService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 🐞 bug

#84 [FIN-279] feat: 글 삭제 시 연관된 다른 테이블 데이터 삭제 및 관리
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/ArticleKeyword.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleLikeRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleKeywordService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature
