Repository SWM-METEOR/finote-backend, pull requests merged in 2023-07, with the labels that each got.

#2 구글 OAuth 로그인 구현
  .DS_Store
  build.gradle
  src/main/java/kr/co/finote/backend/BackendApplication.java
  src/main/java/kr/co/finote/backend/global/authentication/PrincipalDetails.java
  src/main/java/kr/co/finote/backend/global/authentication/auth/PrincipalDetailsService.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
  src/main/java/kr/co/finote/backend/global/config/WebMvcConfig.java
  src/main/java/kr/co/finote/backend/global/converter/StateAttributeConverter.java
  src/main/java/kr/co/finote/backend/global/entity/BaseEntity.java
  src/main/java/kr/co/finote/backend/global/entity/State.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginController.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/main/resources/templates/loginForm.html
Labels: 💪🏻 feature, 👀 review needed, ✍🏻 answer needed

#3 feat: 구글 OAuth 로그인 구현
  build.gradle
  src/main/java/kr/co/finote/backend/global/authentication/PrincipalDetails.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/resources/application.yml
Labels: 👀 review needed, 💻 chore

#10 Rename pull_request_template.md to PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 💻 chore

#13 [FIN-77] feat: 서버 스웨거 연동
  .gitignore
  build.gradle
  src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#15 [FIN-59] feat: 블로그 글 등록
  build.gradle
  src/main/java/kr/co/finote/backend/global/advice/ExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/response/ErrorResponse.java
  src/main/java/kr/co/finote/backend/src/blog/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/blog/domain/Article.java
  src/main/java/kr/co/finote/backend/src/blog/dto/request/ArticleRequest.java
  src/main/java/kr/co/finote/backend/src/blog/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/blog/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
Labels: 💪🏻 feature, 👀 review needed

#16 [FIN-70] 닉네임, 블로그이름, 블로그 URL 중복 검사
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/request/GoogleAccessTokenRequest.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleLoginResponse.java
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleOauthUserInfoResponse.java
  src/main/java/kr/co/finote/backend/src/blog/api/UsersBlogApi.java
  src/main/java/kr/co/finote/backend/src/blog/repository/UsersBlogRepository.java
  src/main/java/kr/co/finote/backend/src/blog/service/UsersBlogService.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#18 [FIN-83] JSESSIONID 생성 및 발급을 통한 유저 식별 기능
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/SaveUserResponse.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/SessionService.java
  src/main/java/kr/co/finote/backend/src/user/utils/SessionUtils.java
Labels: 💪🏻 feature, 👀 review needed

#19 [FIN-91] 유저의 블로그 정보, 닉네임 조회 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/blog/api/UsersBlogApi.java
  src/main/java/kr/co/finote/backend/src/blog/dto/response/BlogResponse.java
  src/main/java/kr/co/finote/backend/src/blog/repository/UsersBlogRepository.java
  src/main/java/kr/co/finote/backend/src/blog/service/UsersBlogService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
Labels: 💪🏻 feature, 👀 review needed

#20 [FIN-69] 추가 정보 등록 API
  src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/blog/service/UsersBlogService.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/AdditionalInfoRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/SaveUserResponse.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#23 [Refactor] User, UsersBlog 도메인 병합
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/ArticleRequest.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/blog/api/UsersBlogApi.java
  src/main/java/kr/co/finote/backend/src/blog/domain/UsersBlog.java
  src/main/java/kr/co/finote/backend/src/blog/repository/UsersBlogRepository.java
  src/main/java/kr/co/finote/backend/src/blog/service/UsersBlogService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/BlogResponse.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 👀 review needed, 💻 chore

#25 [FIN-99] 유저 세션 검증을 위한 interceptor 추가
  src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
  src/main/java/kr/co/finote/backend/global/config/SwaggerConfig.java
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/global/interceptor/SessionInterceptor.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/test/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#26 [FIN-100] feat: Article 도메인과 User 도메인 연결
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/global/interceptor/SessionInterceptor.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature, 👀 review needed

#27 [FIN-94] AI 검색 API 구현
  src/main/java/kr/co/finote/backend/global/authentication/oauth/PrincipalOauth2UserService.java
  src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/AiSearchType.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/AiSearchRequest.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/ChatGptRequest.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/AiSearchResponse.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ChatgptResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/AiSearchService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/utils/ChatGptPromptUtils.java
  src/main/java/kr/co/finote/backend/src/article/utils/ChatGptRequestSender.java
  src/main/java/kr/co/finote/backend/src/article/utils/ChatGptResponseResolver.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#29 [FIN-119] AI 검색 (코드 설명) API
  src/main/java/kr/co/finote/backend/src/article/api/AiSearchApi.java
  src/main/java/kr/co/finote/backend/src/article/utils/ChatGptPromptUtils.java
Labels: 💪🏻 feature, 👀 review needed

#31 [FIN-128] fix: 비로그인 유저 글 작성에 따른 작성자 정보 설정
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
Labels: 🐞 bug

#36 Update README.md
  README.md
Labels: 📜 documentation
