Repository SWM-METEOR/finote-backend, pull requests merged in 2023-09, with the labels that each got.

#87 [FIN-262] 글 조회 시 사용자의 좋아요 여부 응답 필드 추가
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/annotation/Liked.java
  src/main/java/kr/co/finote/backend/global/argumentresolver/LikedArgumentResolver.java
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/cache/ArticleLikeCache.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/CacheService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#88 hotfix: thumbnail 빈 스트링, 글쓰기 경로 수정
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
Labels: 🐞 bug, 👀 review needed

#89 hotfix: 글 수정 API 응답 형식 수정
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature, 👀 review needed

#90 hotfix: Google auth 서버 응답 필드 추가
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleUserInfo.java
Labels: 🐞 bug, 👀 review needed

#91 hotfix: link 필드를 가진 구글 로그인 사용자 오류 해결
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleUserInfo.java
Labels: 🐞 bug

#92 hotfix: code deploy 배포 중 script timeout 발생하는 에러 해결
  appspec.yml
Labels: 🐞 bug, 👀 review needed

#93 [FIN-295] feat: 유저가 좋아요 한 글의 갯수 API
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleLikeRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleLikeService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/LikeCountResponse.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#94 [FIN-293] 좋아요 API 엔드포인트 변경 (닉네임/제목)
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 👀 review needed, 👀 refactor

#95 hotfix: elasticsearch 커넥션 에러 해결
  src/main/java/kr/co/finote/backend/BackendApplication.java
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchConfig.java
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchTester.java
Labels: 🐞 bug, 👀 review needed

#96 [FIN-305] feat: 글 조회 시 팔로우 여부 필드 추가
  src/main/java/kr/co/finote/backend/global/annotation/LoginOptional.java
  src/main/java/kr/co/finote/backend/global/argumentresolver/LoginOptionalArgumentResolver.java
  src/main/java/kr/co/finote/backend/global/argumentresolver/LoginUserArgumentResolver.java
  src/main/java/kr/co/finote/backend/global/config/WebConfig.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/common/service/FollowService.java
Labels: 💪🏻 feature, 👀 review needed

#97 [FIN-296] feat: 내가 좋아요 한 글 리스트 API
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleLikeRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleLikeService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
Labels: 💪🏻 feature, 👀 review needed

#98 [FIN-304] feat: S3 업로드를 위한 Pre-signed url 발급 API
  build.gradle
  src/main/java/kr/co/finote/backend/global/config/S3Config.java
  src/main/java/kr/co/finote/backend/src/common/api/CommonApi.java
  src/main/java/kr/co/finote/backend/src/common/dto/request/FileUploadRequest.java
  src/main/java/kr/co/finote/backend/src/common/dto/response/PresignedUrlResponse.java
  src/main/java/kr/co/finote/backend/src/common/service/S3Service.java
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#99 [FIN-265] 추가 정보 설정 API 수정하기
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/AdditionalInfoRequest.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#100 hotfix: elasticsearch connection 에러 해결 시도
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchTester.java
Labels: 🐞 bug

#101 hotfix: Prod환경의 ElasticSearch Connection 에러 해결 시도
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchTester.java
Labels: 🐞 bug

#103 [FIN-308] feat: 다른 유저의 팔로워 수 API
  src/main/java/kr/co/finote/backend/src/common/api/CommonApi.java
  src/main/java/kr/co/finote/backend/src/common/service/FollowService.java
Labels: 💪🏻 feature, 👀 review needed

#104 refactor: Swagger api 태그 이름 변경
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/user/api/JwtApi.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
Labels: 👀 review needed, 👀 refactor

#106 [FIN-301] feat: 글 등록 시 썸네일 요청 field 추가
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/ArticleRequest.java
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
Labels: 💪🏻 feature, 👀 review needed

#107 [FIN-307] feat: 특정 글에 대한 유저의 좋아요 여부 확인 API
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleLikeCheckResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature, 👀 review needed

#108 [FIN-268] feat: 이메일 인증 코드 발송 및 검증 API
  build.gradle
  src/main/java/kr/co/finote/backend/global/annotation/ValidEmail.java
  src/main/java/kr/co/finote/backend/global/annotation/validator/EmailValidator.java
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/config/RedisCacheConfig.java
  src/main/java/kr/co/finote/backend/global/utils/StringUtils.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleLikeCacheService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailCodeRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailCodeValidationRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/EmailCodeValidationResponse.java
  src/main/java/kr/co/finote/backend/src/user/service/EmailCodeCacheService.java
  src/main/java/kr/co/finote/backend/src/user/service/MailService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
  src/main/java/lombok.config
  src/main/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#110 [FIN-311] feat: 이메일 회원가입 API
  src/main/java/kr/co/finote/backend/global/annotation/ValidPassword.java
  src/main/java/kr/co/finote/backend/global/annotation/validator/PasswordValidator.java
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailJoinRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/BlogResponse.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#111 hotfix/change-response-type-of-validation-api
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/BlogNameDuplicateCheckRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/NicknameDuplicateCheckRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/ValidationBlogNameResponse.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/ValidationNicknameResponse.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#112 [FIN-314] feat: 이메일 중복검사 API
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailDuplicateCheckRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/ValidationEmailResponse.java
  src/main/java/kr/co/finote/backend/src/user/repository/UserRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#113 [FIN-312] feat: 이메일 로그인 API
  src/main/java/kr/co/finote/backend/global/authentication/oauth/google/dto/response/GoogleLoginResponse.java
  src/main/java/kr/co/finote/backend/src/user/api/LoginApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailLoginRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/EmailLoginResponse.java
  src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
  src/main/java/kr/co/finote/backend/src/user/service/LoginService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#114 [FIN-316] feat: 글의 총 좋아요 수 API
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleTotalLikeResponse.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature, 👀 review needed

#116 [FIN-315] feat: 이메일 회원가입 시 검증된 이메일 확인 로직 추가
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/config/RedisCacheConfig.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticlePreviewResponse.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailJoinRequest.java
  src/main/java/kr/co/finote/backend/src/user/service/EmailJoinCacheService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
Labels: 💪🏻 feature, 👀 review needed

#117 [FIN-323] feat: 질문글 생성 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/domain/Keyword.java
  src/main/java/kr/co/finote/backend/src/qna/api/QuestionApi.java
  src/main/java/kr/co/finote/backend/src/qna/domain/Question.java
  src/main/java/kr/co/finote/backend/src/qna/dto/request/PostQuestionRequest.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/PostQuestionResponse.java
  src/main/java/kr/co/finote/backend/src/qna/repository/QuestionRepository.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
Labels: 💪🏻 feature, 👀 review needed

#120 [FIN-326] feat: 질문글 삭제 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/qna/api/QuestionApi.java
  src/main/java/kr/co/finote/backend/src/qna/domain/Question.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
Labels: 💪🏻 feature, 👀 review needed

#121 [FIN-338] feat: 글 조회 API 응답에 thumbnail 필드 추가
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
Labels: 💪🏻 feature, 👀 review needed

#122 hotfix : add-profile-image-field-to-preview
  src/main/java/kr/co/finote/backend/src/article/document/ArticleDocument.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticlePreviewResponse.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
Labels: 💪🏻 feature

#123 hotfix: add-thumbnail-field-to-edit-blog
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/user/domain/User.java
Labels: 💪🏻 feature

#124 [FIN-332] feat: 조회수 로직 구현
  src/main/java/kr/co/finote/backend/BackendApplication.java
  src/main/java/kr/co/finote/backend/global/config/RedisConfig.java
  src/main/java/kr/co/finote/backend/global/entity/BaseEntity.java
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleViewCacheService.java
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
Labels: 💪🏻 feature, 👀 review needed

#125 ArticleService 테스트
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
Labels: 💪🏻 feature

#126 refactor: refresh token 관련 오류 확인
  src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
Labels: 🐞 bug

#127 UserService 유닛테스트
  src/main/java/kr/co/finote/backend/src/user/dto/request/AdditionalInfoRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailCodeRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailCodeValidationRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailJoinRequest.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
  src/test/java/kr/co/finote/backend/src/user/service/UserServiceTest.java
Labels: 💪🏻 feature

#128 UserService 유닛테스트
  src/test/java/kr/co/finote/backend/src/user/service/UserServiceTest.java
Labels: 💪🏻 feature

#129 refactor: refresh token 관련 오류 분석
  src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
Labels: 👀 refactor

#130 hotfix: add no args constructor to request dto
  src/main/java/kr/co/finote/backend/src/article/dto/request/ArticleRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/AdditionalInfoRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailCodeRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailCodeValidationRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailJoinRequest.java
  src/main/java/kr/co/finote/backend/src/user/service/JwtService.java
Labels: 🐞 bug

#131 hotfix: add no args constructor to request dto
  src/main/java/kr/co/finote/backend/src/user/dto/request/EmailJoinRequest.java
Labels: 🐞 bug

#133 hotfix: add repeatable logic of save
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature

#134 [FIN-346] feat: 댓글 작성 API
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Reply.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/ReplyRequest.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/PostReplyResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ReplyRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ReplyService.java
Labels: 💪🏻 feature

#138 [FIN-353] feat: 질문 글에 대한 답변 생성 API
  src/main/java/kr/co/finote/backend/src/qna/api/AnswerApi.java
  src/main/java/kr/co/finote/backend/src/qna/domain/Answer.java
  src/main/java/kr/co/finote/backend/src/qna/dto/request/PostAnswerRequest.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/PostAnswerResponse.java
  src/main/java/kr/co/finote/backend/src/qna/repository/AnswerRepository.java
  src/main/java/kr/co/finote/backend/src/qna/service/AnswerService.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
Labels: 💪🏻 feature, 👀 review needed

#139 [FIN-358] refactor: 글 작성 시간의 시간, 분, 초 표시하기
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticleResponse.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/QuestionResponse.java
Labels: 👀 refactor

#140 [FIN-347] feat: 댓글 리스트 API
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/api/ReplyApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Reply.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ReplyListResponse.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ReplyResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ReplyRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/ReplyService.java
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
Labels: 💪🏻 feature

#141 [FIN-360] feat: 질문글 답변 리스트 API
  src/main/java/kr/co/finote/backend/src/qna/api/AnswerApi.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/AnswerListResponse.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/AnswerResponse.java
  src/main/java/kr/co/finote/backend/src/qna/repository/AnswerRepository.java
  src/main/java/kr/co/finote/backend/src/qna/service/AnswerService.java
Labels: 💪🏻 feature, 👀 review needed

#142 [FIN-355] feat: 댓글 수정 및 삭제 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/article/api/ReplyApi.java
  src/main/java/kr/co/finote/backend/src/article/domain/Reply.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/ReplyService.java
Labels: 💪🏻 feature

#143 [FIN-362] feat: 글 수정, 삭제 시 ES에 반영
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/document/ArticleDocument.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleEsRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/ElasticService.java
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
Labels: 💪🏻 feature

#144 [FIN-378] feat: 프로필 이미지 조회 API
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/ProfileImageUrlResponse.java
Labels: 💪🏻 feature

#145 [FIN-350] 질문 등록, 수정, 삭제 Es 연동
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/global/exception/ConnectException.java
  src/main/java/kr/co/finote/backend/src/qna/document/QuestionDocument.java
  src/main/java/kr/co/finote/backend/src/qna/domain/Question.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/AnswerResponse.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/QuestionResponse.java
  src/main/java/kr/co/finote/backend/src/qna/repository/QuestionEsRepository.java
  src/main/java/kr/co/finote/backend/src/qna/service/AnswerService.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionEsService.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
  src/test/java/kr/co/finote/backend/src/user/service/UserServiceTest.java
Labels: 💪🏻 feature, 👀 review needed

#146 [FIN-388] feat: Article ES 연동로직 수정
  src/main/java/kr/co/finote/backend/global/config/ElasticSearchTester.java
  src/main/java/kr/co/finote/backend/src/article/document/ArticleDocument.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/article/dto/response/ArticlePreviewResponse.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleEsRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleEsService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/article/service/ReplyService.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
  src/main/java/kr/co/finote/backend/src/user/service/UserService.java
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
Labels: 💪🏻 feature

#147 [FIN-348] feat: 카테고리 생성 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/article/domain/Article.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/Category.java
  src/main/java/kr/co/finote/backend/src/user/dto/request/CategoryRequest.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/CategoryResponse.java
  src/main/java/kr/co/finote/backend/src/user/repository/CategoryRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/CategoryService.java
  src/test/java/kr/co/finote/backend/src/article/service/ArticleServiceTest.java
  src/test/java/kr/co/finote/backend/src/user/service/UserServiceTest.java
Labels: 💪🏻 feature

#148 [FIN-387] 답변 생성 API 스펙 변경
  src/main/java/kr/co/finote/backend/src/qna/domain/Answer.java
  src/main/java/kr/co/finote/backend/src/qna/dto/request/PostAnswerRequest.java
Labels: 💪🏻 feature

#149 hotfix: elasticsearch에 데이터 업데이트하는 api 추가
  src/main/java/kr/co/finote/backend/src/article/api/ArticleApi.java
  src/main/java/kr/co/finote/backend/src/article/document/ArticleDocument.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleEsService.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 💪🏻 feature

#150 [FIN-327] feat: Q&A 커뮤니티 질문글 리스트 API
  src/main/java/kr/co/finote/backend/global/argumentresolver/LoginUserArgumentResolver.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/qna/api/QuestionApi.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/QuestionPreviewListResponse.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/QuestionPreviewResponse.java
  src/main/java/kr/co/finote/backend/src/qna/repository/QuestionRepository.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionEsService.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
Labels: 💪🏻 feature, 👀 review needed

#152 [FIN-391] 스마트 드래그 - Q&A
  src/main/java/kr/co/finote/backend/src/qna/api/QuestionApi.java
  src/main/java/kr/co/finote/backend/src/qna/dto/request/InlineQnaRequest.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/InlineQnaResponse.java
  src/main/java/kr/co/finote/backend/src/qna/dto/response/QuestionPreviewResponse.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionEsService.java
  src/main/java/kr/co/finote/backend/src/qna/service/QuestionService.java
Labels: 💪🏻 feature, 👀 review needed

#153 hotfix: 댓글 목록에서 삭제된 것까지 보여주는 문제 해결
  src/main/java/kr/co/finote/backend/src/article/repository/ReplyRepository.java
Labels: 🐞 bug

#154 [FIN-390] feat: 카테고리 수정 및 삭제 API
  src/main/java/kr/co/finote/backend/global/code/ResponseCode.java
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/repository/ReplyRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/domain/Category.java
  src/main/java/kr/co/finote/backend/src/user/repository/CategoryRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/CategoryService.java
Labels: 💪🏻 feature

#155 [FIN-349] feat: 카테고리 목록 API
  src/main/java/kr/co/finote/backend/src/article/repository/ArticleRepository.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/user/api/UserApi.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/CategoryListResponse.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/CategoryResponse.java
  src/main/java/kr/co/finote/backend/src/user/dto/response/PostCategoryResponse.java
  src/main/java/kr/co/finote/backend/src/user/repository/CategoryRepository.java
  src/main/java/kr/co/finote/backend/src/user/service/CategoryService.java
Labels: 💪🏻 feature
