Repository SWM-METEOR/finote-backend, pull requests merged in 2023-10, with the labels that each got.

#156 [FIN-394] feat: @SpringBootTest 테스트 환경 구성
  .github/workflows/build-deploy.yml
  build.gradle
  src/test/java/kr/co/finote/backend/src/user/service/LoginServiceTest.java
  src/test/resources/application.yml
Labels: 👀 review needed, 💻 chore

#157 [FIN-413] feat: CI환경의 테스트 수행
  .github/workflows/build-deploy.yml
  src/test/resources/application.yml
Labels: 👀 review needed, 💻 chore

#158 hotfix: 유저 인증을 위한 URL 검증 로직 수정
  src/main/java/kr/co/finote/backend/global/argumentresolver/LoginUserArgumentResolver.java
  src/main/java/kr/co/finote/backend/global/config/SecurityConfig.java
Labels: 🐞 bug, 👀 review needed

#159 hotfix: 키워드 추출 로직 적용
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
Labels: 🐞 bug

#160 [FIN-422] 메시지 큐 통신 환경 구축
  build.gradle
  src/main/java/kr/co/finote/backend/global/config/SqsConfig.java
  src/main/java/kr/co/finote/backend/src/article/dto/request/FeedRequest.java
  src/main/java/kr/co/finote/backend/src/article/service/ArticleService.java
  src/main/java/kr/co/finote/backend/src/common/service/FeedService.java
  src/main/java/kr/co/finote/backend/src/common/utils/SqsSender.java
  src/main/resources/application.yml
  src/test/java/kr/co/finote/backend/src/common/utils/SqsSenderTest.java
  src/test/resources/application.yml
Labels: 💪🏻 feature, 👀 review needed

#161 [FIN-411] feat: Sentry 연동
  build.gradle
  src/main/java/kr/co/finote/backend/global/advice/GlobalExceptionHandler.java
  src/main/java/kr/co/finote/backend/global/exception/InvalidInputException.java
  src/main/java/kr/co/finote/backend/global/exception/NotFoundException.java
  src/main/java/kr/co/finote/backend/global/exception/UnAuthorizedException.java
  src/main/resources/application.yml
Labels: 💪🏻 feature
